### ISSUE TITLE
合适的Python版本

### ISSUE THREAD

**Issue by YMMF007** [wadx2019/qvpo#1]
您好，我在复现您的代码时，遇见了一个问题，即由于不知道合适的Python版本，导致Python依赖包无法正常安装，我已经尝试过3.7、3.8、3.10均未果。故想询问一下您，谢谢~

**Comment by wadx2019** [comment]
Thanks for your interest! My python version is 3.10.14. If you still have any problem, please show me your reported error information.

**Comment by YMMF007** [comment]
您好，我下载了3.10.14的Python版本。
![image](https://github.com/user-attachments/assets/80e6b7aa-60b4-4404-a662-49834e4a4461)
这是报错

**Comment by wadx2019** [comment]
Got it! You should first install setuptools==65. and wheel==0.38.

**Comment by YMMF007** [comment]
哦哦哦哦，好的，谢谢您~

**Comment by YMMF007** [comment]
您好，能再麻烦您看一下吗，还是不行。我试图把gym先注释掉，也不行。b并且我确定Python版本是对的。
![image](https://github.com/user-attachments/assets/8b0abd19-212a-496f-b940-fa8142afa3a8)
![image](https://github.com/user-attachments/assets/bd1c2060-4023-47a3-927a-36d7bd6108c8)
![image](https://github.com/user-attachments/assets/4e5eae14-dfdc-484e-92ad-c6808fbcd0a4)

**Comment by wadx2019** [comment]
I think you need to type gym==0.21.0 rather than 0.21

**Comment by YMMF007** [comment]
![image](https://github.com/user-attachments/assets/c740eccd-891a-4d26-80d2-830fa005f108)

**Comment by YMMF007** [comment]
sad

**Comment by wadx2019** [comment]
reduce your pip version
